name: Actions Workflow SQL Server

on:
  push:
    branches: [ main ]

jobs:
  run-sql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Startup Container
        shell: bash
        run: |
          # In this scenario with a fresh container used for testing,
          # it is acceptable to use a plain-text password
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Admin123" \
          -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools pip wheel
          # Use the latest published version for myself :)
          python -m pip install tox-gh-actions
      - name: Test with tox
        run: tox
        continue-on-error: false